#!groovy

def runFile() {
    def rootDir = pwd()
    def applicationName = "app1"
    def common = load "${rootDir}/common.Groovy"

    common.deployToMarathon("${rootDir}/${applicationName}/marathon.json", "")
}

return this