#!groovy

def runFile() {
    def rootDir = pwd()
    def common = load "${rootDir}/common.Groovy"

    def applicationName = "SparkStreamingExample"
    def targetJar = "SparkStreamingExample-1.0.0.jar"

    // build maven project
    common.buildMavenProject(applicationName)

    // push to S3
    common.pushToS3(${applicationName}/target/${targetJar}", targetJar)

    // deploy to marathon
    def marathonURI = common.getMarathonURI(targetJar)
    common.deployToMarathon("${rootDir}/${applicationName}/marathon.json", marathonURI)
}

return this